/*
-- Query: SELECT * FROM bmf.produits
LIMIT 0, 1000

-- Date: 2017-06-13 16:51
*/
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (1,'Tablette tactile 10,1\'\' LCD TFT - Résolution 1280 x 800 px - Mediatek Cortex A53 MT8163 Quad Core (1,3 GHz) - Stockage 16 Go - RAM 1 Go - Port Micro USB 2.0 - Port Micro SD - Réseau WiFi - Bluetooth 4.0','Iconia One 10 - WiFi - Bleu','acer-1.jpg',400,50000,4);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (2,'Tablette Tactile 10,1\" Full HD IPS - Résolution 1920 x 1080 px WUXGA - Processeur Quad-Core (1,5 GHz) - Stockage 32 Go - Port microSD - RAM 2 Go - Réseau Wifi - Bluetooth 4.0 - Webcam avant : 2 MPx - Webcam','Iconia Tab 10 - WiFi - Noir','acer-2.jpg',300,5000,4);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (3,'Tablette tactile 7\' IPS - 1024 x 600 px - Technologie IPS - MTK MT8127 Quad Core (1,3 GHz) - Stockage 16 Go - RAM 1 Go - Port Micro SD - Port Micro USB 2.0 - Wifi - Bluetooth 4.0 - Webcam avant : 0.3 Mpx','Iconia One 7 - WiFi - Noir','acer-2.jpg',350,5000,4);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (4,'Tablette tactile 8\' - 1280 x 800 px - Technologie IPS - MTK MT8163 Quad Core (1,3 GHz) - Stockage 16 Go - RAM 1 Go - Port Micro USB 2.0 - Wifi - Bluetooth 4.0 - Webcam avant : 0.3 Mpx - Webcam arrière : 5','Iconia One 8 - WiFi - Blanc','acer-4.jpg',250,5000,4);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (5,'Tablette Tactile 10,1\" IPS FHD - Résolution 1920 x 1200 px - Processeur Quad-Core (1,5 GHz) - Stockage 32 Go - Port microSD - Port micro HDMI - RAM 2 Go -  Réseau Wifi - Bluetooth 4.0 - Webcam avant: 2 MPx','Iconia Tab 10 - Noir','acer-5.jpg',450,5000,4);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (6,'Tablette Tactile 10,1\" Full HD - Résolution 1920 x 1200 px - Technologie IPS - Processeur Intel® Atom™ Z3735F Quad Core (1,83 GHz) - Stockage 32 Go - Port micro SD - Port micro USB 2.0 ','conia Tab 10 A3-A30 32 Go','acer-6.jpg',550,5000,4);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (7,'Tablette Tactile 7\" - Résolution 1024 x 600 px - Processeur Mediatek Quad-Core (1,3 GHz) - Stockage 8 Go - Port microSD - Port carte Sim - RAM 1 Go - Réseau Wi-Fi - Bluetooth 4.0 - Webcam avant : 0.3 MPx','70 Xenon Color - WiFi - 3G','archos-1.jpg',400,5000,6);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (8,'Tablette tactile 10,1\' Full HD - 1920 x 1200 px - Technologie IPS - Mediatek MTK 8163A Quad Core (1,3 GHz) - Stockage 32 Go - RAM 2 Go - Port Micro SD - Port Micro USB - Port Mini HDMI - Wifi - Bluetooth','101b Oxygen - Wifi - Gris','archos-2.jpg',420,5000,6);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (9,'Tablette tactile 10,1\' Full HD - 1920 x 1200 px - Technologie IPS - Mediatek MTK 8163A Quad Core (1,3 GHz) - Stockage 32 Go - RAM 2 Go - Port Micro SD - Port Micro USB - Port Mini HDMI - Wifi - Bluetooth','101b Oxygen - WiFi - Gris ','archos-3.jpg',420,5000,6);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (10,'div class \"block 50 block text \" Tablette Tactile 10,1\" Résolution 1024 x 600 px Processeur Quad Core 1,3 GHz Stockage 32 Go Port MicroSD RAM 1 Go Réseau WiFi Bluetooth 4.0 Webcam avant','101e Neon - 503214 - WiFi','archos-4.jpg',420,5000,6);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (11,'Tablette tactile 8\' - 1920 x 1200 px - Technologie IPS - Mediatek MTK 8163A Quad Core (1,3 GHz) - Stockage 32 Go - RAM 2 Go - Port Micro SD - Port Micro USB - Port Micro HDMI - Wifi - Bluetooth 4.0','80 Oxygen-8 Full HD IPS 32 Go','archos-5.jpg',420,5000,6);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (12,'Tablette tactile 7\'\' - 1024 x 600 px - Technologie IPS - Mediatek MT8127 Cortex A7 Quad-Core (1,3 GHz) - Stockage 16 Go - RAM 1 Go - Port Micro SD jusqu\'à 64 Go - Port Micro USB - Wifi - Bluetooth 4.0','70 Platinium-16 Go-Wifi-Blanc','archos-6.jpg',540,5000,6);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (13,'Tablette tactile 10,1\'\' - 1920 x 1200 px LCD - Technologie IPS - HiSilicon Kirin 930 Octo Core (2,0 GHz) - Stockage 64 Go - RAM 3 Go - Port Micro SD - Port Micro USB - 4G - Wifi - Bluetooth 4.0 - Caméra','MediaPad- 64 Go - 4G - Argent','huawei-1.jpg',340,5000,8);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (14,'Tablette tactile 10,1\'\' - 1920 x 1200 px LCD - Technologie IPS - HiSilicon Kirin 930 Octo Core (2,0 GHz) - Stockage 16 Go - RAM 2 Go - Port Micro SD - Port Micro USB - 4G - Wifi - Bluetooth 4.0 - Caméra','MediaPad M2 10.0-10,1\"IPS','huawei-2.jpg',240,4000,8);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (15,'Tablette tactile 10,1\' - 1920 x 1200 px LCD - Technologie IPS - HiSilicon Kirin 930 Octo Core (2,0 GHz) - Stockage 64 Go - RAM 3 Go - Port Micro SD - Port Micro USB - Wifi - Bluetooth 4.0 - Caméra Avant','Tablette MediaPad 64 Go Argent','huawei-3.jpg',340,4000,8);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (16,'Tablette Tactile 8\" Full HD - Résolution 1920 x 1200 px - Technologie IPS - Processeur Kirin 930 Octa A53 Octo Core (2,0 GHz) - Stockage 16 Go - Port micro SD - Port USB - Mémoire vive 2 Go - Réseau Wifi','MediaPad 8\'-16 Go-Wifi-Argent','huawei-4.jpg',240,4000,8);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (17,'Nos appareils sont vendus neuf, libre opérateur avec boîte scellée,il possède une fonction communication réseau , il peut être utilisé avec toutes les cartes Sim. Garantie du fabricant de 12 à 24 mois','MediaPad 8\' 16 Gb Lte argent','huawei-5.jpg',240,4000,8);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (18,'Tablette tactile 9,6\' - 1280 x 800 px - Technologie IPS - MSM 8916 Quad A53 64-bit (1,2 GHz) - Stockage 16 Go - RAM 1 Go - Port Micro SD - Wifi - Bluetooth 4.0 - Caméra Avant : 2 Mpx - Caméra Arrière : 5','MediaPad-16Go-Wifi-Blanc Gris','huawei-6.jpg',240,4000,8);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (19,'Tablette tactile 9,7\'\' Retina - 2048 x 1536 px - Puce A9X avec architecture 64 bits - Stockage 32 Go - RAM 2 Go - Port Nano-SIM - Wifi - Bluetooth 4.2 - Caméra Avant : 5 Mpx - Caméra Arrière : 12 Mpx','iPad Pro 32 Go WiFi Or','ipad-1.jpg',800,5000,5);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (20,'Tablette tactile 9,7\' Retina - 2048 x 1536 px - Puce A9X avec architecture 64 bits - Stockage 32 Go - RAM 2 Go - Port Nano-SIM - Wifi - Bluetooth 4.2 - Caméra Avant : 5 Mpx - Caméra Arrière : 12 Mpx','iPad 128 Go-WiFi Gris Sidéral','ipad-2.jpg',800,5000,5);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (21,'Tablette tactile 9,7\' Retina - 2048 x 1536 px - Puce A9X avec architecture 64 bits - Stockage 32 Go - RAM 2 Go - Port Nano-SIM - Wifi - Bluetooth 4.2 - Caméra Avant : 5 Mpx - Caméra Arrière : 12 Mpx','iPad Pro 32 Go-WiFi Or Rose','ipad-3.jpg',600,5000,5);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (22,'Tablette tactile 9,7\' Retina - 2048 x 1536 px - Puce A9X avec architecture 64 bits - Stockage 32 Go - RAM 2 Go - Port Nano-SIM - Wifi - Bluetooth 4.2 - Caméra Avant : 5 Mpx - Caméra Arrière : 12 Mpx','iPad Pro-Wifi-Argent','ipad-4.jpg',700,5000,5);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (23,'Tablette tactile 9,7\' Retina - 2048 x 1536 px - Puce A9X avec architecture 64 bits - Stockage 256 Go - RAM 2 Go - Port Nano-SIM - 4G LTE - Wifi - Bluetooth 4.2 - Caméra Avant : 5 Mpx - Caméra Arrière : 12','iPad mini 128 Go WiFi+Cellular','ipad-5.jpg',650,5000,5);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (24,'Tablette Tactile 12,9\" - Résolution 2732 x 2048 px - Écran Retina - Technologie IPS - Puce A9X avec architecture 64 bits Coprocesseur de mouvement M9 - Stockage 32 Go - Réseau Wifi - Bluetooth 4.2 - Webcam','iPad Pro-32 Go-Wifi Argent','ipad-6.jpg',700,5000,5);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (25,'Tablette tactile 7\'\' (1024 x 600 px) - Technologie IPS - Processeur MediaTek Quad Core (1,3 GHz) - Stockage 16 Go - RAM 1 Go - Port Micro SD - Wifi - Webcam avant : 0.3 Mpx - Webcam arrière : 2 Mpx- 0,300','Tab3-710 -7\"-16 Go-Wifi-Noir','lenovo-1.jpg',600,5000,2);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (26,'Tablette Tactile 7\" - Résolution 1024 x 600 px - Processeur Quad-Core (1,3 GHz) - Stockage 16 Go - Port microSD - RAM 1 Go - Réseau Wifi - Bluetooth 4.0 - Webcam avant: 0.3 Mpx - Webcam arrière: 2 Mpx - 300','Tab2 16 Go-Wifi-Bleu Marine','lenovo-2.jpg',600,5000,2);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (27,'Tablette Tactile 7\" - Résolution 1024 x 600 px - Processeur Quad-Core (1,3 GHz) - Stockage 16 Go - Port microSD - RAM 1 Go - Réseau Wifi - Bluetooth 4.0 - Webcam avant: 0.3 Mpx - Webcam arrière: 2 Mpx - 300','Tab2 16 Go Bleu Marine','lenovo-2.jpg',600,5000,2);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (28,'Tablette Tactile 7\" - Résolution 1024 x 600 px - Processeur Quad-Core (1,3 GHz) - Stockage 16 Go - Port microSD - RAM 1 Go - Réseau Wifi - Bluetooth 4.0 - Webcam avant: 0.3 Mpx - Webcam arrière: 2 Mpx - 300','Tab2 16Go Bleu Marine','lenovo-2.jpg',600,5000,2);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (29,'div class \"block 50 block text \" Tablette tactile 10,1\' 1280 x 800 px Technologie IPS RAM 2 Go Qualcomm APQ8009 1,3 GHz Stockage 16 Go Port Micro SD Port Micro USB Wifi Bluetooth 4.','TAB2-10,1\'-16 Go-Wifi-Blanc','lenovo-3.jpg',600,5000,2);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (30,'div class \"block 50 block text \" Tablette tactile 10,1\' 1280 x 800 px Technologie IPS Processeur Qualcomm APQ8009 Quad Core Stockage 16 Go RAM 2 Go Port Micro SD Port Micro USB Wifi ','Tab2 - 10,1\'16 Go-Wifi-Blanc','lenovo-4.jpg',600,5000,2);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (31,'Tablette tactile 10,1\' - 1280 x 800 px - Technologie IPS - RAM 1 Go - Qualcomm APQ8009 (1,3 GHz) Quad Core 32 bit - Stockage 16 Go - Port Micro SD - Port Micro USB - Wifi - Bluetooth 4.0 - 0,509 Kg','TAB2-10,1\'16Go Bleu marine','lenovo-5.jpg',600,5000,2);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (32,'div class \"block 50 block text \" Tablette tactile 10,1\' 1280 x 800 px Technologie IPS Processeur Qualcomm APQ8009 Quad Core Stockage 16 Go RAM 2 Go Port Micro SD Port Micro USB Wifi ','Tab 3 710F- WiFi - Bleu','lenovo-6.jpg',600,5000,2);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (33,'Processeur Intel® Core™ i5-6300U (2,4 GHz / 3,0 GHz Turbo) - Ecran tactile 12,3\'\' PixelSense - Résolution de 2736 x 1824 pixels - RAM 4 Go - SSD 128 Go - Chipset graphique Intel® HD Graphics 520 - Réseau','Pro 128 Go-Intel Core i5','microsoft-1.jpg',500,5000,3);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (34,'Processeur Intel® Core™ i5-6300U (2,4 GHz / 3,0 GHz Turbo) - Ecran tactile 12,3\'\' PixelSense - Résolution de 2736 x 1824 pixels - RAM 4 Go - SSD 128 Go - Chipset graphique Intel® HD Graphics 520 - Réseau','Pro 256 Go-Intel Core i7','microsoft-2.jpg',600,5000,3);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (35,'Tablette Tactile 10,1\" - Résolution 1920 x 1200 px WUXGA - Processeur Octo Core (1,6 GHz) - Stockage 16 Go - Lecteur Micro SD - Port micro USB 2.0 - Mémoire vive 2 Go - Réseau Wifi - Bluetooth 4.2 - Webcam','Galaxy Tab A6 - WiFi - Blanc','samsung-1.jpg',500,5000,1);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (36,'Tablette Tactile 9,7\" - Résolution 2048 x 1536 px QXGA - Processeur Octo Core (1,8 GHz) - Stockage 32 Go - Lecteur Micro SDHC - Port micro USB 2.0 - Mémoire vive 3 Go - Réseau Wifi - Bluetooth 4.1 - Webcam','Galaxy Tab S2- WiFi - Blanc','samsung-2.jpg',500,5000,1);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (37,'Tablette Tactile 9,7\" - Résolution 2048 x 1536 px QXGA - Processeur Octo Core (1,8 GHz) - Stockage 32 Go - Lecteur Micro SDHC - Port micro USB 2.0 - Mémoire vive 3 Go - Réseau Wifi - Bluetooth 4.1 - Webcam','Galaxy Tab S2-WiFi-Noir','samsung-3.jpg',500,5000,1);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (38,'OS Android 5.1 - Processeur 1.5 GHz Quad-Core - Résolution 1280 x 800 - Mémoire RAM 1.5 Go - Stockage 8 Go - Caméras 2 et 5 Mpx - Wi-Fi, 4G et Bluetooth 4.0','Galaxy Tab A 4G - Blanc','samsung-4.jpg',500,5000,1);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (39,'Tablette Tactile 9,7\" - Résolution 2048 x 1536 px QXGA - Processeur Quad-Core (2,15 GHz) - Stockage 32 Go - Port microSD - USB 3.1 Type-C - RAM 4 Go -  Réseau Wifi - 4G - Bluetooth 4.2 - Webcam avant: 5 MPx','Galaxy Tab S3- 4G - Noir','samsung-5.jpg',500,5000,1);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (40,'Processeur Octo Core (1,6 GHz) - Stockage 16 Go - Lecteur Micro SD - Port micro USB 2.0 - Mémoire vive 2 Go - Réseau Wifi - Bluetooth 4.2 - Webcam a','Tactile 10,1\" 1920 x 1200 px','samsung-6.jpg',500,5000,1);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (41,'Processeur Intel® Atom™ Z3735F (1,33 GHz / 1,83 GHz Rafale) - Ecran tactile 10,1\" IPS - Résolution de 1280 x 800 pixels - RAM 2 Go - Stockage eMMC 32 Go - Chipset graphique Intel HD Graphics - Réseau sans','Ordinateur p 2-en-1 Gris','thomson-1.jpg',400,5000,7);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (42,'Tablette Tactile/PC 2 en 1 8.9\" - Résolution 1280 x 800 px - Intel Atom Z3735F - Stockage 32 Go - eMMC - Port Micro USB - Mémoire vive 2 Go - Réseau Wifi - Bluetooth 4.0 - Windows 10','2 EN 1 8,9 - 9','thomson-2.jpg',400,5000,7);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (43,'Tablette Tactile 10.1\" - Résolution 1024 x 600 px - Processeur Quad Core A33 - Stockage 8 Go - Lecteur Micro SD - Port Micro USB - Mémoire vive 1 Go - Réseau Wifi - Bluetooth 4.0 - Android 5.1 Lollipop ','TEO QUAD 10','thomson-3.jpg',400,5000,7);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (44,'Tablette Tactile 9\" - Résolution 1024 x 600 px - Processeur Quad Core A33 - Stockage 8 Go - Port MicroSD - Port Micro USB - RAM 1 Go - Réseau Wifi - Bluetooth 4.0 - Android 5.1 Lollipop','TEO QUAD 9\' AVEC COACH SPORTIF','thomson-4.jpg',400,5000,7);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (45,'Processeur Intel® Atom™ Z3735F (1,33 GHz / 1,83 GHz Rafale - Quad-Core) - Ecran tactile 10,1\" IPS HD / G-Sensor  - Résolution de 1280 x 800 pixels - RAM 1 Go - SSD de 32 Go - Chipset graphique Intel HD','Tablette 2-en-1 Prestige 10\'','thomson-5.jpg',400,5000,7);
INSERT INTO `produits` (`id_produit`,`description`,`designation`,`photo`,`prix`,`quantite`,`id_categorie`) VALUES (46,'Prestige 7\' QC A33 Z3735G Stockage 8 Go RAM 1 Go Ecran 7\' Android 5.0 LolliPop','Prestige 7','thomson-6.jpg',400,5000,7);
